### ISSUE TITLE
Cannot re-add deleted emails to UserOfferings

### ISSUE THREAD

**Issue by ruihuasui** [classtranscribe/WebAPI#45] opened 2020-06-30 21:57 UTC
The API `UserOfferings/AddUsers/{offeringId}/{roleName}` cannot add a previously deleted email

**Comment by chirantan31** [comment] 2020-07-01 03:30
#32 should fix this.

**Comment by asherdale** [comment] 2020-10-04 20:42
Closing because this is duplicate of #32

**Closed by asherdale** 2020-10-04 20:42 UTC
Labels: bug
